apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mern

resources:
  - namespace.yaml
  - mongo-statefulset.yaml
  - server-deployment.yaml
  - server-service.yaml
  - server-hpa.yaml
  - client-deployment.yaml
  - client-service.yaml
  - ingress.yaml
  - etl-cronjob.yaml

# mongo-secret created out-of-band; see mongo-secret.example.yaml
